### ISSUE TITLE
invalid index 6 in unpicklee cache of length 5

### ISSUE THREAD

**Issue by glidester** [scala/pickling#109] opened 2014-01-29 11:15 UTC
Hi. I'm trying to use pickling to serialize (in JSON) the securesocial.core.SocialUser class. It pickles ok but when I try to unpickle the json string representation it throws an java.lang.Error with the message "invalid index 6 in unpicklee cache of length 5".

I've created an Eclipse scala worksheet that demonstrates the issue:

```scala
import scala.pickling.json.JSONPickle
import scala.pickling._
import json._
import securesocial.core.SocialUser

object unpickle {
  
  val serializedSocialUser = """{
  "tpe": "securesocial.core.SocialUser",
  "firstName": "Tim",
  "lastName": "Wil,
  "fullName": "Tim Wil",
  "identityId": {
    "userId": "gr@gmail.com",
    "providerId": "userpass"
  },
  "email": {
    "tpe": "scala.Some[scala.Any]",
    "x": {
      "tpe": "java.lang.String",
      "value": "gr@gmail.com"
    }
  },
  "avatarUrl": {
    "tpe": "scala.Some[scala.Any]",
    "x": {
      "tpe": "java.lang.String",
      "value": "http:\/\/www.gravatar.com\/avatar\/8c206bf0d875b1233643b0a9df563b83?d=404"
    }
  },
  "authMethod": {
    "method": "userPassword"
  },
  "oAuth1Info": {
    "tpe": "scala.None.type"
  },
  "oAuth2Info": { "$ref": 6 },
  "passwordInfo": {
    "tpe": "scala.Some[scala.Any]",
    "x": {
      "tpe": "securesocial.core.PasswordInfo",
      "hasher": "bcrypt",
      "password": "$2a$10$JxfRk8LELi23ycJ4Xy1smueexEMghkTFydAfsmpDNzzX5IR\/6tVBe",
      "salt": { "$ref": 6 }
    }
  }
}"""                                              

  val deSerialized = JSONPickle(serializedSocialUser).unpickle[SocialUser]
}
```

(the json string is the one generated by calling pickle.value on the SocialUser object.

Thanks,

Tim

**Comment by glidester** [comment] 2014-01-29 11:43
Some more info:

I created my own implementation of the securesocial.core.Identity trait (that SocialUser implements) and that pickles and unpickles fine.

Looking at the json produced when pickling my own implementation hi-lights some differences with the json produced pickling the SocialUser implementation.

Here is the json produced from pickling my implementation:

``` json
{
  "tpe": "model.SecureSocialIdentityImp",
  "firstName": "Tim",
  "lastName": "Wil,
  "fullName": "Tim Wil",
  "identityId": {
    "userId": "gr@gmail.com",
    "providerId": "userpass"
  },
  "email": {
    "tpe": "scala.Some[java.lang.String]",
    "x": "gr@gmail.com"
  },
  "avatarUrl": {
    "tpe": "scala.Some[java.lang.String]",
    "x": "http:\/\/www.gravatar.com\/avatar\/8c206bf0d875b1233643b0a9df563b83?d=404"
  },
  "authMethod": {
    "method": "userPassword"
  },
  "oAuth1Info": {
    "tpe": "scala.None.type"
  },
  "oAuth2Info": {
    "tpe": "scala.None.type"
  },
  "passwordInfo": {
    "tpe": "scala.Some[securesocial.core.PasswordInfo]",
    "x": {
      "hasher": "bcrypt",
      "password": "$2a$10$KNWN3WEXDaWBCXuwvwZQf.BFFFRN5x1CcelvAzbLwEAnm\/rDGP7Wa",
      "salt": {
        "tpe": "scala.None.type"
      }
    }
  }
}
```

I suspect the issue is with this section of the non-working json representation (in my first post):

``` scala
"oAuth2Info": { "$ref": 6 },
```

Although there are some other differences such as in the non-working version I get:

```
"email": {
"tpe": "scala.Some[scala.Any]",
"x": {
"tpe": "java.lang.String",
"value": "gr@gmail.com"
}
```

and in the working version it looks like:

```
"email": {
    "tpe": "scala.Some[java.lang.String]",
    "x": "glidester@gmail.com"
  }
```

**Comment by jsuereth** [comment] 2015-08-13 12:56
This appears to be a bug with the `shareing` aspects of pickling.  Closing as duplicate of #260 which has a minimal reproduction.

**Closed by jsuereth** 2015-08-13 12:56 UTC
