### ISSUE TITLE
Failed to pickle/unpickle java.util.UUID

### ISSUE THREAD

**Issue by dallmeier** [scala/pickling#250] opened 2014-12-09 14:56 UTC
The following test fails for me on bea06fb88b1f252cead5a7720b5d7bc14ccac85e of branch 0.10.x:

    package pickling.run

    import org.scalatest.FunSuite
    import scala.pickling._, Defaults._
    import json._

    class NestedUuidTest extends FunSuite {

      test("main") {
        val uuid = java.util.UUID.randomUUID()
        val pickle : JSONPickle = uuid.pickle
        val unpickled = pickle.unpickle[java.util.UUID]
        assert (uuid == unpickled)
      }
    }

Output:

```
c112a87c-21e4-4446-925a-fc7ead8c88ea did not equal 00000000-0000-0000-0000-000000000000
org.scalatest.exceptions.TestFailedException: c112a87c-21e4-4446-925a-fc7ead8c88ea did not equal 00000000-0000-0000-0000-000000000000
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:498)
	at org.scalatest.FunSuite.newAssertionFailedException(FunSuite.scala:1559)
	at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:413)
	at pickling.run.NestedUuidTest$$anonfun$1.apply$mcV$sp(nesteduuid.scala:13)
	at pickling.run.NestedUuidTest$$anonfun$1.apply(nesteduuid.scala:9)
	at pickling.run.NestedUuidTest$$anonfun$1.apply(nesteduuid.scala:9)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:158)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1121)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1559)
	at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:155)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:167)
	at org.scalatest.FunSuite.runTest(FunSuite.scala:1559)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:200)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:200)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:200)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1559)
	at org.scalatest.Suite$class.run(Suite.scala:1423)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1559)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:204)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:204)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:204)
	at org.scalatest.FunSuite.run(FunSuite.scala:1559)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.run(Runner.scala:883)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:137)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```
I was particulary surprised to see this fail because special support for UUIDs was added in 29b8581e2ddf2ebe58b3c94a49a647a5a455d30d .

I also tested this on 0.9.x and it fails.

**Comment by eed3si9n** [comment] 2015-02-08 10:37
I was able to reproduce this using Pickling 0.10.0.

**Comment by eed3si9n** [comment] 2015-02-08 10:41
Closing this as a duplicate of #122.

**Closed by eed3si9n** 2015-02-08 10:41 UTC
Labels: enhancement
