### ISSUE TITLE
"invalid index 1 in unpicklee cache of length 1" during unpickling where object ref is repeated

### ISSUE THREAD

**Issue by lilZ420** [scala/pickling#74] opened 2013-11-11 19:24 UTC
## steps (0.10.0)

```scala
scala-pickling> console
[info] Starting scala interpreter...
[info] 
Welcome to Scala version 2.11.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_51).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import scala.pickling._, Defaults._, json._
import scala.pickling._
import Defaults._
import json._

scala> case class StringProp(prop: String) {}
defined class StringProp

scala> class PropTest(val prop1: StringProp, val prop2: StringProp) {}
defined class PropTest

scala> val obj = StringProp("test")
obj: StringProp = StringProp(test)

scala> val pickle = new PropTest(obj, obj).pickle.unpickle[PropTest]
```

## problems

```
scala> val pickle = new PropTest(obj, obj).pickle.unpickle[PropTest]
scala.pickling.PicklingException: error in unpickle of primitive unpickler 'scala.pickling.refs.Ref':
tag in unpickle: 'scala.pickling.refs.Ref'
message:
fatal error: invalid index 1 in unpicklee cache of length 1
  at scala.pickling.pickler.PrimitivePickler.unpickle(Primitives.scala:31)
  at $line12$readiwiwiwiwPropTestUnpickler$macro$4$2$$line11$readiwiwiwiwStringPropUnpickler$macro$12$2$.unpickle(<console>:20)
  at $line12$readiwiwiwiwPropTestUnpickler$macro$4$2$.unpickle(<console>:20)
  at scala.pickling.Unpickler$class.unpickleEntry(Pickler.scala:79)
  at $line12$readiwiwiwiwPropTestUnpickler$macro$4$2$.unpickleEntry(<console>:20)
  at scala.pickling.functions$.unpickle(functions.scala:11)
  at scala.pickling.UnpickleOps.unpickle(Ops.scala:23)
  ... 43 elided
```

## original report

Here is a sample use case to produce an Invalid Index exception when unpickling:

```scala
import scala.pickling._
import json._
object JsonTest extends App {
  val obj = StringProp("test")
  val pickle = new PropTest(obj, obj).pickle.unpickle[PropTest]
}
case class StringProp(prop: String) {}
class PropTest(val prop1: StringProp, val prop2: StringProp) {}
```

As reported on StackOverflow:
http://stackoverflow.com/questions/19436070/invalid-index-unpickling-where-object-ref-is-repeated

**Comment by eed3si9n** [comment] 2015-02-08 06:20
I was able to reproduce the problem using Pickling 0.10.0.

**Comment by eed3si9n** [comment] 2015-02-08 10:20
This one is older, but since there's a workaround presented in #240 I'm closing this as the duplicate.

**Closed by eed3si9n** 2015-02-08 10:20 UTC
Labels: bug
