### ISSUE TITLE
Replace directSubclasses annotation by a macro driven implementation

### ISSUE THREAD

**Issue by kiritsuku** [scala/pickling#313] opened 2015-04-02 10:25 UTC
Since annotations are not carefully supported in Scala (we can't do `@directSubclasses(Array(classOf[Object.type]))`), scala-pickling shouldn't rely on them. Instead it should use a similar implementation to what is provided by safepickles [Autogen.children](https://github.com/fsist/safepickle/blob/6a28c9b4764cc20ab784698abcd0acba49e2993e/src/main/scala/com/fsist/safepickle/Autogen.scala#L851).

**Comment by jsuereth** [comment] 2015-08-12 20:00
@sschaef That implementation suffers the same limitations as us, due to scala compiler bug.  AFAIK we DO try to do the same thing in terms of discovering subclasses.  The issue is subclass discovery is compeltely dependent on compilation order (has the compiler seen the subclasses yet) and is therefore super flaky.

Unless we get a new solutiong from scalac (which is unlikely, it's not a use case they probably want to support) I think we're stuck with the annotation approach.

Marking this wontfix for now, but I'd love to hear alternatives.

**Closed as completed by jsuereth** 2015-08-12 20:00 UTC
Labels: enhancement, wontfix
