### ISSUE TITLE
Cannot unpickle a case class with a field name called "columns"

### ISSUE THREAD

**Issue by PhilAndrew** [scala/pickling#95] opened 2013-12-16 14:08 UTC
Final update: This is a strange bug, IF I have pickle or unpickle calls in my large class then this sort of bug appears. If I move the pickle or unpickle out to a smaller class which just deals with pickling then this bug goes away.
So I tend to make sure that my pickle and unpickle calls are then located in a small dedicated class to the pickling in a different Scala file.

Update: Moving this code out into a separate Rectangle.scala file solved the problem.

Update: Ummmm... I'm wrong, its not the word columns.

case class Rectangle(x: Int, y: Int, width: Int, height: Int)

case class RowImageRectangle(rectangle: Rectangle, columns: List[Rectangle])

val result = str.unpickle[List[RowImageRectangle]]

> compile
[info] Compiling 1 Scala source to /Users/orsa/home/projects/stampup/saturn/invoiceocr/target/scala-2.10/classes...
[error] 
[error]      while compiling: /Users/orsa/home/projects/stampup/saturn/invoiceocr/src/main/scala/com/orsa/invoiceocr/image/OcrImage.scala
[error]         during phase: jvm
[error]      library version: version 2.10.3
[error]     compiler version: version 2.10.3
[error]   reconstructed args: -bootclasspath /Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/JObjC.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/classes:/Users/orsa/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.10.3.jar -classpath /Users/orsa/home/projects/stampup/saturn/invoiceocr/target/scala-2.10/classes:/Users/orsa/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.10.3.jar:/Users/orsa/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.10.3.jar:/Users/orsa/.ivy2/cache/org.specs2/specs2_2.10/jars/specs2_2.10-2.2.3.jar:/Users/orsa/.ivy2/cache/org.scalaz/scalaz-core_2.10/bundles/scalaz-core_2.10-7.0.2.jar:/Users/orsa/.ivy2/cache/org.scalaz/scalaz-concurrent_2.10/bundles/scalaz-concurrent_2.10-7.0.2.jar:/Users/orsa/.ivy2/cache/org.scalaz/scalaz-effect_2.10/bundles/scalaz-effect_2.10-7.0.2.jar:/Users/orsa/.ivy2/cache/com.github.nscala-time/nscala-time_2.10/jars/nscala-time_2.10-0.6.0.jar:/Users/orsa/.ivy2/cache/joda-time/joda-time/jars/joda-time-2.3.jar:/Users/orsa/.ivy2/cache/org.joda/joda-convert/jars/joda-convert-1.2.jar:/Users/orsa/.ivy2/cache/com.typesafe.akka/akka-actor_2.10/jars/akka-actor_2.10-2.2.3.jar:/Users/orsa/.ivy2/cache/com.typesafe/config/bundles/config-1.0.2.jar:/Users/orsa/.ivy2/cache/com.github.nikita-volkov/sext/jars/sext-0.2.3.jar:/Users/orsa/.ivy2/cache/org.clapper/grizzled-scala_2.10/jars/grizzled-scala_2.10-1.1.4.jar:/Users/orsa/.ivy2/cache/jline/jline/jars/jline-2.6.jar:/Users/orsa/.ivy2/cache/com.fasterxml.uuid/java-uuid-generator/bundles/java-uuid-generator-3.1.3.jar:/Users/orsa/.ivy2/cache/io.spray/spray-can/bundles/spray-can-1.2-RC3.jar:/Users/orsa/.ivy2/cache/io.spray/spray-io/bundles/spray-io-1.2-RC3.jar:/Users/orsa/.ivy2/cache/io.spray/spray-util/bundles/spray-util-1.2-RC3.jar:/Users/orsa/.ivy2/cache/io.spray/spray-http/bundles/spray-http-1.2-RC3.jar:/Users/orsa/.ivy2/cache/org.parboiled/parboiled-scala_2.10/bundles/parboiled-scala_2.10-1.1.6.jar:/Users/orsa/.ivy2/cache/org.parboiled/parboiled-core/bundles/parboiled-core-1.1.6.jar:/Users/orsa/.ivy2/cache/io.spray/spray-routing/bundles/spray-routing-1.2-RC3.jar:/Users/orsa/.ivy2/cache/io.spray/spray-httpx/bundles/spray-httpx-1.2-RC3.jar:/Users/orsa/.ivy2/cache/org.jvnet.mimepull/mimepull/jars/mimepull-1.9.3.jar:/Users/orsa/.ivy2/cache/com.chuusai/shapeless_2.10/jars/shapeless_2.10-1.2.4.jar:/Users/orsa/.ivy2/cache/io.spray/spray-testkit/jars/spray-testkit-1.2-RC3.jar:/Users/orsa/.ivy2/cache/com.typesafe.akka/akka-testkit_2.10/bundles/akka-testkit_2.10-2.2.3.jar:/Users/orsa/.ivy2/cache/io.spray/spray-json_2.10/jars/spray-json_2.10-1.2.5.jar:/Users/orsa/.ivy2/cache/com.sksamuel.scrimage/scrimage-core_2.10/jars/scrimage-core_2.10-1.3.9.jar:/Users/orsa/.ivy2/cache/org.apache.sanselan/sanselan/bundles/sanselan-0.97-incubator.jar:/Users/orsa/.ivy2/cache/log4j/log4j/bundles/log4j-1.2.17.jar:/Users/orsa/.ivy2/cache/commons-io/commons-io/jars/commons-io-2.4.jar:/Users/orsa/.ivy2/cache/org.scalatest/scalatest_2.10/jars/scalatest_2.10-1.9.1.jar:/Users/orsa/.ivy2/cache/org.scala-lang/scala-actors/jars/scala-actors-2.10.0.jar:/Users/orsa/.ivy2/cache/com.sksamuel.scrimage/scrimage-filters_2.10/jars/scrimage-filters_2.10-1.3.9.jar:/Users/orsa/.ivy2/cache/com.novus/salat-util_2.10/jars/salat-util_2.10-1.9.4.jar:/Users/orsa/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.2.jar:/Users/orsa/.ivy2/cache/org.scala-lang/scalap/jars/scalap-2.10.3.jar:/Users/orsa/.ivy2/cache/com.novus/salat-core_2.10/jars/salat-core_2.10-1.9.4.jar:/Users/orsa/.ivy2/cache/org.mongodb/casbah-core_2.10/jars/casbah-core_2.10-2.6.4.jar:/Users/orsa/.ivy2/cache/org.mongodb/casbah-commons_2.10/jars/casbah-commons_2.10-2.6.4.jar:/Users/orsa/.ivy2/cache/org.mongodb/mongo-java-driver/jars/mongo-java-driver-2.11.3.jar:/Users/orsa/.ivy2/cache/org.mongodb/casbah-query_2.10/jars/casbah-query_2.10-2.6.4.jar:/Users/orsa/.ivy2/cache/org.json4s/json4s-native_2.10/jars/json4s-native_2.10-3.2.5.jar:/Users/orsa/.ivy2/cache/org.json4s/json4s-core_2.10/jars/json4s-core_2.10-3.2.5.jar:/Users/orsa/.ivy2/cache/org.json4s/json4s-ast_2.10/jars/json4s-ast_2.10-3.2.5.jar:/Users/orsa/.ivy2/cache/com.thoughtworks.paranamer/paranamer/jars/paranamer-2.5.6.jar:/Users/orsa/.ivy2/cache/org.mockito/mockito-all/jars/mockito-all-1.9.0.jar:/Users/orsa/.ivy2/cache/org.streum/configrity-core_2.10/jars/configrity-core_2.10-1.0.0.jar:/Users/orsa/.ivy2/cache/org.scala-lang/scala-pickling_2.10/jars/scala-pickling_2.10-0.8.0-SNAPSHOT.jar
[error] 
[error]   last tree to typer: Literal(Constant(com.orsa.invoiceocr.image.Rectangle))
[error]               symbol: null
[error]    symbol definition: null
[error]                  tpe: Class(classOf[com.orsa.invoiceocr.image.Rectangle])
[error]        symbol owners: 
[error]       context owners: anonymous class removeWatermark$1 -> package image
[error] 
[error] == Enclosing template or block ==
[error] 
[error] Template( // val <local $anonfun>: <notype>, tree.tpe=com.orsa.invoiceocr.image.removeWatermark$1
[error]   "scala.runtime.AbstractFunction1$mcVI$sp", "scala.Serializable" // parents
[error]   ValDef(
[error]     private
[error]     "_"
[error]     <tpt>
[error]     <empty>
[error]   )
[error]   // 6 statements
[error]   DefDef( // final def apply(y: Int): Unit
[error]     <method> final <triedcooking>
[error]     "apply"
[error]     []
[error]     // 1 parameter list
[error]     ValDef( // y: Int
[error]       <param> <triedcooking>
[error]       "y"
[error]       <tpt> // tree.tpe=Int
[error]       <empty>
[error]     )
[error]     <tpt> // tree.tpe=Unit
[error]     Apply( // def apply$mcVI$sp(y: Int): Unit, tree.tpe=Unit
[error]       OcrImage$$anonfun$com$orsa$invoiceocr$image$OcrImage$$removeWatermark$1.this."apply$mcVI$sp" // def apply$mcVI$sp(y: Int): Unit, tree.tpe=(y: Int)Unit
[error]       "y" // y: Int, tree.tpe=Int
[error]     )
[error]   )
[error]   DefDef( // def apply$mcVI$sp(y: Int): Unit
[error]     <method> <specialized> <triedcooking>
[error]     "apply$mcVI$sp"
[error]     []
[error]     // 1 parameter list
[error]     ValDef( // y: Int
[error]       <param> <triedcooking>
[error]       "y"
[error]       <tpt> // tree.tpe=Int
[error]       <empty>
[error]     )
[error]     <tpt> // tree.tpe=Unit
[error]     Apply( // final override def foreach$mVc$sp(f: Function1): Unit in class Range, tree.tpe=Unit
[error]       RichInt.this.until$extension0(scala.this.Predef.intWrapper(0), OcrImage$$anonfun$com$orsa$invoiceocr$image$OcrImage$$removeWatermark$1.this.ocrImage$1.image().width())."foreach$mVc$sp" // final override def foreach$mVc$sp(f: Function1): Unit in class Range, tree.tpe=(f: Function1)Unit
[error]       Block( // tree.tpe=Function1
[error]         {}
[error]         Typed( // tree.tpe=Function1
[error]           Apply( // def <init>(arg$outer: com.orsa.invoiceocr.image.removeWatermark$1,y$1: Int): com.orsa.invoiceocr.image.anonfun$apply$mcVI$sp$2, tree.tpe=com.orsa.invoiceocr.image.anonfun$apply$mcVI$sp$2
[error]             new anonymous class anonfun$apply$mcVI$sp$2."<init>" // def <init>(arg$outer: com.orsa.invoiceocr.image.removeWatermark$1,y$1: Int): com.orsa.invoiceocr.image.anonfun$apply$mcVI$sp$2, tree.tpe=(arg$outer: com.orsa.invoiceocr.image.removeWatermark$1)com.orsa.invoiceocr.image.anonfun$apply$mcVI$sp$2
[error]             // 2 arguments
[error]             This("$anonfun")final class removeWatermark$1 extends runtime.AbstractFunction1$mcVI$sp with Serializable in package image, tree.tpe=com.orsa.invoiceocr.image.removeWatermark$1
[error]             "y" // y: Int, tree.tpe=Int
[error]           )
[error]           <tpt> // tree.tpe=Function1
[error]         )
[error]       )
[error]     )
[error]   )
[error]   DefDef( // final def apply(v1: Object): Object
[error]     <method> final <bridge>
[error]     "apply"
[error]     []
[error]     // 1 parameter list
[error]     ValDef( // v1: Object
[error]       <param> <triedcooking>
[error]       "v1"
[error]       <tpt> // tree.tpe=Object
[error]       <empty>
[error]     )
[error]     <tpt> // tree.tpe=Object
[error]     Block( // tree.tpe=runtime.BoxedUnit
[error]       Apply( // final def apply(y: Int): Unit, tree.tpe=Unit
[error]         OcrImage$$anonfun$com$orsa$invoiceocr$image$OcrImage$$removeWatermark$1.this."apply" // final def apply(y: Int): Unit, tree.tpe=(y: Int)Unit
[error]         Apply( // def unbox(x: Object): Int in object Int, tree.tpe=Int
[error]           "scala"."Int"."unbox" // def unbox(x: Object): Int in object Int, tree.tpe=(x: Object)Int
[error]           "v1" // v1: Object, tree.tpe=Object
[error]         )
[error]       )
[error]       "scala"."runtime"."BoxedUnit"."UNIT" // final val UNIT: runtime.BoxedUnit in object BoxedUnit, tree.tpe=runtime.BoxedUnit
[error]     )
[error]   )
[error]   ValDef( // private[this] val ocrImage$1: com.orsa.invoiceocr.image.OcrImage
[error]     private <local> <synthetic> <paramaccessor> <triedcooking>
[error]     "ocrImage$1"
[error]     <tpt> // tree.tpe=com.orsa.invoiceocr.image.OcrImage
[error]     <empty>
[error]   )
[error]   ValDef( // val mutableImage$1: com.sksamuel.scrimage.MutableImage
[error]     <synthetic> <paramaccessor> <triedcooking>
[error]     "mutableImage$1"
[error]     <tpt> // tree.tpe=com.sksamuel.scrimage.MutableImage
[error]     <empty>
[error]   )
[error]   DefDef( // def <init>(ocrImage$1: com.orsa.invoiceocr.image.OcrImage,mutableImage$1: com.sksamuel.scrimage.MutableImage): com.orsa.invoiceocr.image.removeWatermark$1
[error]     <method> <triedcooking>
[error]     "<init>"
[error]     []
[error]     // 1 parameter list
[error]     ValDef( // ocrImage$1: com.orsa.invoiceocr.image.OcrImage
[error]       <param> <synthetic> <triedcooking>
[error]       "ocrImage$1"
[error]       <tpt> // tree.tpe=com.orsa.invoiceocr.image.OcrImage
[error]       <empty>
[error]     )
[error]     ValDef( // mutableImage$1: com.sksamuel.scrimage.MutableImage
[error]       <param> <synthetic> <triedcooking>
[error]       "mutableImage$1"
[error]       <tpt> // tree.tpe=com.sksamuel.scrimage.MutableImage
[error]       <empty>
[error]     )
[error]     <tpt> // tree.tpe=com.orsa.invoiceocr.image.removeWatermark$1
[error]     Block( // tree.tpe=Unit
[error]       // 3 statements
[error]       Assign( // tree.tpe=Unit
[error]         OcrImage$$anonfun$com$orsa$invoiceocr$image$OcrImage$$removeWatermark$1.this."ocrImage$1" // private[this] val ocrImage$1: com.orsa.invoiceocr.image.OcrImage, tree.tpe=com.orsa.invoiceocr.image.OcrImage
[error]         "ocrImage$1" // ocrImage$1: com.orsa.invoiceocr.image.OcrImage, tree.tpe=com.orsa.invoiceocr.image.OcrImage
[error]       )
[error]       Assign( // tree.tpe=Unit
[error]         OcrImage$$anonfun$com$orsa$invoiceocr$image$OcrImage$$removeWatermark$1.this."mutableImage$1" // val mutableImage$1: com.sksamuel.scrimage.MutableImage, tree.tpe=com.sksamuel.scrimage.MutableImage
[error]         "mutableImage$1" // mutableImage$1: com.sksamuel.scrimage.MutableImage, tree.tpe=com.sksamuel.scrimage.MutableImage
[error]       )
[error]       Apply( // def <init>(): scala.runtime.AbstractFunction1$mcVI$sp in class AbstractFunction1$mcVI$sp, tree.tpe=scala.runtime.AbstractFunction1$mcVI$sp
[error]         OcrImage$$anonfun$com$orsa$invoiceocr$image$OcrImage$$removeWatermark$1.super."<init>" // def <init>(): scala.runtime.AbstractFunction1$mcVI$sp in class AbstractFunction1$mcVI$sp, tree.tpe=()scala.runtime.AbstractFunction1$mcVI$sp
[error]         Nil
[error]       )
[error]       ()
[error]     )
[error]   )
[error] )
[error] 
[error] == Expanded type of tree ==
[error] 
[error] ConstantType(value = Constant(com.orsa.invoiceocr.image.Rectangle))
[error] 
[error] uncaught exception during compilation: java.io.IOException
[error] File name too long
[error] two errors found
[error] (compile:compile) Compilation failed
[error] Total time: 8 s, completed Dec 16, 2013 10:08:22 PM
>

**Comment by eed3si9n** [comment] 2015-02-08 06:52
```
[error] uncaught exception during compilation: java.io.IOException
[error] File name too long
```

This is a duplicate of #10. One of things to try would be

``` scala
scalacOptions ++= Seq("-Xmax-classfile-name", "254")
```

**Closed by eed3si9n** 2015-02-08 06:52 UTC
