### ISSUE TITLE
Case Class + single integer field yields "hasMatchingSymbol reported error"

### ISSUE THREAD

**Issue by andrewslack** [scala/pickling#352] opened 2015-07-30 12:47 UTC
I am attempting a simple exercise from the console.  I presume I am doing something stupid but there is very little that could go wrong, please advise:

scala> import scala.pickling.Defaults._, scala.pickling.json._
import scala.pickling.Defaults._
import scala.pickling.json._

scala> case class Person(id: Integer)
defined class Person

scala> Person(100)
res2: Person = Person(100)

scala> Person(100).pickle
<console>:25: genPickler is not a valid implicit value for scala.pickling.Pickler[Person] because:
hasMatchingSymbol reported error: stepping aside: repeating itself
              Person(100).pickle
...
...
<console>:25: genPickler is not a valid implicit value for scala.pickling.Pickler[Integer] because:
hasMatchingSymbol reported error: exception during macro expansion:
scala.pickling.PicklingException: No fields are captured. You need a custom pickler to handle this.
    at scala.pickling.PicklerMacros$$anonfun$pickleLogic$1.unifiedPickle$1(Macros.scala:239)
...
...

I doubt I have to write a custom pickler for the Person case class.  Do I?

Other Info:
scalaVersion := "2.11.6"
libraryDependencies += "org.scala-lang.modules" %% "scala-pickling" % "0.10.1"

**Comment by phaller** [comment] 2015-07-30 13:08
The issue is the use of Java's `Integer` instead of `Int`.

**Comment by andrewslack** [comment] 2015-07-30 13:15
Sheesh, really.  Thanks!

**Comment by jsuereth** [comment] 2015-07-30 14:09
We should probably have picklers for the "big" java versions of primitives.  CLosing this as resolved for now, open an enhancement if you want the java picklers out of the box.

**Closed as completed by jsuereth** 2015-07-30 14:09 UTC
Labels: question
